---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Update OS
    package:
      name: '*'
      state: latest

  - name: Install Basic packages
    package:
      name: ['vim', 'zip', 'bash-completion', 'wget', 'tmux']