# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  
  config.vm.define "ig" do |serverig|
    serverig.vm.box = "ubuntu/focal64"
    serverig.vm.network "private_network", ip: "10.0.0.2"
    serverig.vm.network "forwarded_port", guest: 80, host: 8080
    serverig.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.cpus = 1
    end
    config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y nginx
      sudo ufw allow 'Nginx HTTP'
    SHELL
  end
  config.vm.define "frontend" do |frontend|
    frontend.vm.box = "ubuntu/focal64"
    frontend.vm.network "private_network", ip: "10.0.0.11"
    frontend.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.cpus = 1
    end
    frontend.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y nodejs
    SHELL
  end
  config.vm.define "backend" do |backend|
    backend.vm.box = "ubuntu/focal64"
    backend.vm.network "private_network", ip: "10.0.0.12"
    backend.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.cpus = 1
    end
    backend.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt install -y python3-pip
      pip install fastapi uvicorn
    SHELL
  end
end
